spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/polarsophia/config-store.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 10s
    threads:
      max: 100
      min-spare: 5

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  server:
    port: 9000
